### ISSUE TITLE
[APP-480] Let users change their account's email address 

### ISSUE THREAD

**Issue by arcalinea** [bluesky-social/social-app#101]
Users may lose access to old email accounts, or simply want to change where they get notifications from us. 

Not an urgent priority, but we should add this at some point. 

Should make sure we verify the new email address before adding to account.

<sub>[APP-480](https://linear.app/blueskyweb/issue/APP-480/let-users-change-their-accounts-email-address)</sub>

**Comment by Leseratte10** [comment]
Looking at the description of this issue, it says 

> Users may lose access to old email accounts, ...

Is this issue actually fixed, then? As mentioned in #3894 (with a slightly confusing title), there seems to be no way to change the email address on your BlueSky account once you lost access to your old email account. 

Even if you have 2FA disabled, or still have a logged-in session somewhere, or have authenticated with a future non-email 2FA method like TOTP, it looks like even today you need to confirm a link sent to your *old* email address to be able to change your email, which makes this process useless if you actually lose access to your old email account. 

Or is there a dedicated "I lost my email account" process that I'm missing? Can this issue be re-opened and a proper feature to allow changing an account email without having access to the old email address be implemented?

**Comment by Tamschi** [comment]
Looking at how common account theft is on Discord[^1], not having email somewhat mandatorily in the loop seems like a bad idea (since social media accounts can be quite valuable for for phishers etc.), but maybe an email like

> Someone is trying to change the email address associated with <account> from <old email> to <new email>.
>
> [Accept now] [Reject within 7 days]
>
> **If no action is taken, change will be permitted.**

along with a prominent warning on the website during that time frame (and the option to cancel there) would work.

[^1]: I see Discord accounts taken over pretty frequently myself, even in relatively small servers. I'm not sure how much of an issue this is in general, but subjectively the problem is quite prominent.

**Comment by Leseratte10** [comment]
As for Discord (or other) accounts getting taken over, I guess that's an issue that could be prevented with proper TOTP 2FA instead of just email 2FA. I hope this will be added to Bluesky soon as well.

But yeah, an email template exactly like this is what I had in mind. Send an email to the old address, and if it is still in use and there's indeed an account takeover attempt, the original owner can cancel the takeover. But if it's either allowed by the owner (when he still has access to the email) or that time period of 7 days is over (when they no longer have access to the email) then the account can be migrated to the new email address.

**Comment by Tamschi** [comment]
Somehow my brain skipped typing out "unrecoverable" in "unrecoverable account theft".

You're right, this wouldn't do much about the initial takeover, just would prevent it from becoming permanent by letting the user do a password reset easily if necessary (which should also auto-cancel the process).
