### ISSUE TITLE
Reconsider “skeet” and “reskeet”

### ISSUE THREAD

**Issue by BookshopLeslie** [bluesky-social/social-app#1060]
I’m sure it’s challenging to come up with brand-exclusive recognizable terms for things that exist on other platforms, but please consider an alternative to the “skeet” before Beta ends. Users frequently mention dislike of this term; I’ve yet to see a skeet in favor of the name.

I humbly suggest that there is no real need to come up with a unique word and that simply using generic terms like “post” and “repost” or “share” and “reshare” would be clearer and much more popular. 
/

**Comment by pfrazee** [comment]
"Post" and "Repost" are the official terms. Users informally call them skeets and we haven't found any meaningful ways to stop them.

**Comment by Zero3K** [comment]
There's blocking those words or just ignoring people who use those words. I think they call them that because bluesky sounds like brewsky (like the name for an alcoholic beverage).

**Comment by pfrazee** [comment]
Heh you know, one thing we could do is introduce a "profanity filter" that replaces words (aka `hell` -> `heck`) and it could be used for this

**Comment by monicaellerose** [comment]
Im curious actually, I remember when facebook came out with languages like 15 years ago, it had a 'pirate language', so I am wondering if it would be possible to have skeet/reskeet be able to show up if someone viewed it under an english MEME language option or something?  
if thats possible, then maybe someone from the community could just add a simple language update to it? 

the reason i really liked the reskeet-skeet was because it helped build an entire culture around a silly word that made it known that it was not twitter/twitter replacement.
