### ISSUE TITLE
Add reply sorting options

### ISSUE THREAD

**Issue by skunecuscre1** [bluesky-social/social-app#1103]
It'd be nice to have the ability to sort thread replies in different ways (for example, most liked replies first) instead of having it be strictly chronological.

I think there should be a default option you can choose to change, as well as the ability to manually set it on individual posts (kinda like reddits comment sorting thing)

**Comment by pfrazee** [comment]
Yeah I've been thinking about something like this as well

**Comment by str4d** [comment]
#1356 changed the core of the default sorting algorithm from "newest first" (i.e. chronological) to "most liked replies first". This is what I believe the current default sort order to be:
- Original Poster's replies always first.
  - Within OP's replies, oldest-first (reverse chronological).
- Remaining posts sorted in order of moderation score, lowest-first.
  - Within each moderation score band, most-liked-first.
    - For posts with equal likes, newest-first (chronological).

 It's unclear to me whether this is just sorting the immediate replies, or whether it recursively sorts all branches of the thread?

In any case, having the option to choose how to sort the unmoderated replies (presumably the vast majority of replies, and the ones most users think of as replies) still seems like a good idea.

**Comment by Bossett** [comment]
The default here is really important - and I don't think it should be 'by likes'; since it will have the negative effects detailed in #1407 (and in all the top replies of https://bsky.app/profile/bsky.app/post/3k6t3d3wkxv26 when sorted by likes 👀). I would advocate the old way being the default, with a sort control in the thread itself (i.e. under the OP) that a user can click to change (so it functions more like a 'peek').

I think a global user setting, or a change to the site-wide default, should maybe wait until it's possible to a) lock threads, or moderate replies (beyond just 'blocking') and, b) manage threads & reply chains in the UI better?

If you look at that linked thread - it's not sorted by 'healthy engagement', it's sorted by 'dunks and complaints that the majority agree with' (and also sorry that happened Paul - pile-ons suck).

**Comment by pfrazee** [comment]
This has been added in the upcoming 1.51 release
