### ISSUE TITLE
Rename "Porn" label to "Explicit" for Moderation Filter Consistency

### ISSUE THREAD

**Issue by ericvolp12** [bluesky-social/social-app#1189]
The currently existing content warning labels are inconsistent with the Moderation/Content-Filtering policy toggles.

The self-labeling toggles should have their titles and copy updated to be consistent.

Current self-labeling options:
![image](https://github.com/bluesky-social/social-app/assets/1617325/a211e950-5fe4-49c6-b8a6-3ae3213855ea)

Current Moderation settings:
![image](https://github.com/bluesky-social/social-app/assets/1617325/1ec5a545-e7d4-4676-b4d8-b638030b81fc)

Below is a table mapping the self labels to the moderation labels:

| **Self-Label** | **Subtitle**                      | **Moderation Label**   | **Moderation Subtitle**           |
|----------------|-----------------------------------|------------------------|-----------------------------------|
| Suggestive     | Pictures meant for adults.        | Sexually Suggestive    | Does not include nudity           |
| Nudity         | Artistic or non-erotic nudity.    | Other Nudity           | Including non-sexual and artistic |
| Porn           | Sexual activity or erotic nudity. | Explicit Sexual Images | i.e. pornography                  |

I'd propose we change the Self Labels to:
- `Suggestive`
- `Artistic Nudity`
- `Explicit`

Or something like that if it fits in the UI.

**Comment by SenpaiSharp** [comment]
Hard disagree with moving away from the word porn and the notion that it is somehow less descriptive and blurry than terms like sexually explicit activity. This is a Carlin bit.

**Comment by HeyItsLollie** [comment]
"Pornography" is a completely unambiguous and succinct term. All that the longer-form description really achieves is a veneer of Corporate Safe language.

**Comment by Potato22** [comment]
(apologies for horrendous English in advance)
I slightly fear that without using the "corporate safe language" where it outright just says "porn" might introduce reasons from these 'taboo purists' to outright block it or to countries that inherit high religion ideologies to block it completely just because it has 'porn' in one of the buttons, sounds ridiculous, but it's a real reason countries would unironically consider.

I'm not sure if what I'm saying even made sense, I'm all ears for feedbacks.
