### ISSUE TITLE
Vertical scrolling input should move the Feeds bar horizontally

### ISSUE THREAD

**Issue by MetaflameDragon** [bluesky-social/social-app#1192]
**Is your feature request related to a problem? Please describe.**

Currently, the top Feeds bar behaves like a regular sideways-scrollable view, so you can (only) scroll sideways with Shift+Mousewheel.

**Describe the solution you'd like**

In addition to being draggable with LMB, the top Feeds bar should respond to regular Mousewheel input as sideways scrolling. When I hover my mouse over the Feeds bar, it would be more convenient to scroll to move sideways instead of dragging (intuitive, but requires more mouse movement) or Shift-scrolling (there's no reason to scroll the bar vertically).

**Additional context**

I'm unsure about how this would work with two-axis scroll inputs, such as a two-finger gesture on a laptop touchpad (which may allow for free bidirectional movement). It makes sense to respect horizontal scrolling there, but receiving vertical scrolling would be translated to horizontal too.

**Comment by pfrazee** [comment]
@estrattonbailey you think you can hit this?

**Comment by estrattonbailey** [comment]
Hey! Appreciate you reaching out and suggesting this 🙂

It's definitely a valid request, but as you say, the browser-built-in and commonly known way to scroll horizontally with a mousewheel is `Shift + Mousewheel`. We try to be very judicious about changing the default behaviors of browsers, as some users may be surprised by unusual behavior.

I'm going to close for now, but we'll leave this here in case others feel the same. It's possible that we'll need to rework the feeds UX in general, since some users do have a lot of custom feeds. We'll keep this in mind for that!
