### ISSUE TITLE
Play videos from direct link

### ISSUE THREAD

**Issue by soapingtime** [bluesky-social/social-app#1289]
**Is your feature request related to a problem? Please describe.**

Videos aren't displayed properly without clicking on the link - killing engagement for any cool projects

**Describe the solution you'd like**

Add a playable embed with the default player that plays the video, and add a thumbnail based on the first frame

**Describe alternatives you've considered**

[Player cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/player-card) like twitter does? Not a big fan of this because it has the same problem of killing engagement 

**Additional context**

Example post: https://bsky.app/profile/did:plc:mbdv5fpty2wlssfwwpys2boh/post/3k5vpxekc3k27

Example screenshot:

![example screenshot](https://github.com/bluesky-social/social-app/assets/135167145/2ef8c1b3-bcb9-47ae-9706-36f86a7488d3)

**Comment by mschwendener** [comment]
Videos are on the roadmap: https://github.com/bluesky-social/social-app/issues/1052

**Comment by boytwink** [comment]
> Videos are on the roadmap

I don't think embeds are though?

**Comment by pfrazee** [comment]
Embeds to third party services aren't atm. I'm not overly fond of the performance of the embedded players, personally, but I'm open to discussing it

**Comment by P4tr0ll** [comment]
Would the embeded video be played directly from the external URL?
If so wouldn't this be prone to abuses like?:
- Changing the source file to a different content at a later date or depending on other factors like country (Regular posts are not editable).
- Collecting user info (IP, user agent etc.) when connecting to the external URL. (Users are more beware when they know they're knowingly clicking on links, but not when displaying external sources).

**Comment by boytwink** [comment]
I don't think either of these are problems that aren't present with normal web sites though. As long as you convey that it's from a website then I don't think it should matter too much

**Comment by TodePond** [comment]
If I post a youtube link, I'd expect it to embed, like it does on X

**Comment by HeyItsLollie** [comment]
> Embeds to third party services aren't atm. I'm not overly fond of the performance of the embedded players, personally, but I'm open to discussing it

Surprised by this tbh. I would've figured that support for third-party embeds would come long before native audio/video media support, especially considering the comparatively lower cost for implementing embeds VS native media support, and the high demand for media support in general.

I'm going to just roll off a bunch of thoughts regarding this.

Firstly, the simple fact is people expect embeds to work. If you post a YouTube link on Twitter, Cohost, Tumblr, even Discord, it will embed. The same goes for SoundCloud, Bandcamp, Streamable and Imgur in some cases. You can just play media from another platform without having to leave the platform you're currently using.

From a creator's point of view, having that media be able to embed directly in a post is especially important. It's one less point of friction - a user can see the post, click on the embed, and experience it. If they want to view the embedded content more directly, the embed will often give the option to view it in a dedicated window. Otherwise, it's just as easy for the user to hit "back" and continue reading their feed.

Bluesky lacks support for gifs, videos, and audio. Media support on Bluesky has been in high demand for a long time. Embeds would provide an effective stopgap for this. People will happily adapt to posting their game-dev WIPs or their stream clips via YouTube, Twitch, Streamable, etc, just as long as they have *something* they can use while they wait for native support.

Finally, the file formats typically associated with these sorts of media types are *costly* for storage. Being able to take advantage of embedding from other media platforms isn't just a little nice-to-have thing, it's going to be important for offsetting the financial cost of hosting a Bluesky instance in the first place.

**Comment by timonsku** [comment]
I would also love to see media embeds to be possible. Even if it starts with being limited to well known platforms like YouTube and Vimeo.
That seems like a low hanging fruit compared to the high effort and cost of media handling on the social server.

Unlike Twitter or Mastodon it would be nice if those would also work on mobile and not just web. On these other platforms they make you go to the website instead of playing the embed in the app directly.

A lot of content I create is video which I currently can not share on Bluesky effectively.
For more professional content creators its also a very important tool that the video views go through the platform they host on. Twitter was always a rough place for YouTube and Music creators due to the massive derating that such links would get.
I'm hoping that Bluesky can be more equitable there but it would first need to allow a more seamless integration of external media. Cohost does this really quite well.

**Comment by fenarinarsa** [comment]
For the tracking issues, what's can be done is to request the embedded player only when the users click/tap on the card. I think that's what the Mastodon/Fediverse clients do.

Also btw it would be cool to support other services than YouTube, and also PeerTube players.

**Comment by adamatic-me** [comment]
I would love showing the embedded player.  People are know to be much more likely to interact with stuff that does not take them away from the site. 

Maybe just from a whitelisted group of sites?  It seems relatively easy compared to hosting the videos yourself, and gives much of the benefit for video creators.

I just prototyped the Vimeo player by pasting in the embed code into dev tools, and it looks fine.

![image](https://github.com/bluesky-social/social-app/assets/146130101/33a09db6-9551-48cd-9d82-31e815d73206)

**Comment by pfrazee** [comment]
I have a branch where I was able to prove it's possible to get a decent embedded player experience. Sadly it's gotta wait while other features take priority, but my biggest concern was jank and I now think, yeah, it can happen

**Comment by TodePond** [comment]
Ship it! You got this!

**Comment by timonsku** [comment]
With the big release out, is there a chance we could get this integrated in the new year? 👀

**Comment by pfrazee** [comment]
In fact we did!

**Comment by timonsku** [comment]
oh nice, did I miss it or is it not merged yet?

**Comment by pfrazee** [comment]
It's only supported for certain platforms like youtube (and we want to add more like vimeo). We can't support any arbitrary host because of moderation concerns

**Comment by TodePond** [comment]
amazing!

**Comment by timonsku** [comment]
> It's only supported for certain platforms like youtube (and we want to add more like vimeo). We can't support any arbitrary host because of moderation concerns

Thats totally reasonable! Tho its not been part of the latest update or? For me YouTube links are still just cards on web and Android app.

**Comment by pfrazee** [comment]
are you on 1.61?

**Comment by timonsku** [comment]
Ok yes now its working on web and just got the ability to make an update on Android too.
Thanks, this is great!
![grafik](https://github.com/bluesky-social/social-app/assets/2370185/e3255074-0788-4fc5-a1b5-ff46687a9d5d)

**Comment by timonsku** [comment]
One small bug on at least Firefox that the preview thumbnail is not showing, its grey until you play the video.

**Comment by zaxbowow** [comment]
Why was this issue closed?  Inability to play video in-place is a major engagement killer for sites hosting the embed, a diminished experience, and a technical inferiority to how YouTube, X and SoundCloud embeds work.

**Comment by samuelawachie** [comment]
> Why was this issue closed? Inability to play video in-place is a major engagement killer for sites hosting the embed, a diminished experience, and a technical inferiority to how YouTube, X and SoundCloud embeds work.

So right now, you want to watch an embedded video, here's a redirection to the website. Another video 30 secs later, here's another unneeded redirection. Yet another video, and others? Here's a redirection to make you happy. This is amateur hour programming. Ridiculous!
