### ISSUE TITLE
Same emojis in Chrome on Windows as on Mac

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#1347]
**Is your feature request related to a problem? Please describe.**

I wanted to quote post something with the feather emoji, to add it to the birder feeds, but that emoji does not exist in Chrome on Windows. 

**Describe alternatives you've considered**

To just accept it ;-) 

---

Edit: same is true for Firefox on Windows vs. Chrome

**Comment by ansh** [comment]
Have you tried copy-pasting the emoji from somewhere else?

**Comment by mschwendener** [comment]
No; the feather emoji also doesn't display on Windows, only displays a little rectangle of some sort, so I wouldn't know what I'm copying. 

I know copy&paste would work technically, because I did that while there was no emoji picker for desktop yet.

**Comment by ansh** [comment]
Unfortunately, that is not under our control, and is different based on the OS and the version.

One way we could solve this is by having our own emoji icon set, making it different from any other platform. But, that seems to degrade the experience for many more users and is a pretty large undertaking (there are thousands of emojis!).

Therefore, this issue is out of scope for Bluesky.

**Comment by ppoutine** [comment]
I think it's bad if a bunch of emojis are rendered as broken just because the client device has an incomplete set.

The [Windows emoji set](https://emojipedia.org/microsoft) for example is *extremely* incomplete. That's a very common use case!

Other platforms like Twitter/FB render using their own emoji set, so people are used to posting e.g. flag emojis and the salute emoji, which are not contained in sets like Microsoft's.

I hope Bsky reconsiders this choice and implements something like Twemoji

**Comment by surfdude29** [comment]
There's actually a draft PR open for adding Twemoji: #4862

Perhaps Twemoji could be used on platforms that have poor emoji support, like Windows, with native emojis used elsewhere?
