### ISSUE TITLE
Can't find bsky-user's in app- 

### ISSUE THREAD

**Issue by Pka78** [bluesky-social/social-app#1853]
I tried to search through the application for a user with a certain ID: akuuttigeriatri.bsky.social. It was noticed that users can't be found through the application, with browser can be searched using NICK or username.

Some users i can find, usually if account is pretty old - but mainly i dont find them. I have also received some reports that my account pka78.bsky.social can't be found trough app, but you can find trough web-page. 
I think this problem could be easily reproduce, just try to find any user that you haven't followed / signed and user doesn't follow you.

**Comment by mschwendener** [comment]
> can't be found trough app, but you can find trough web-page.

I see the opposite, since the federation (?) 
searching for user pfrazee brings me one hit instead of 4, both in Firefox and Chrome on Mac. Version 1.56.0

Searching in iOS finds all 4, Version 1.56.0 (3)

<img width="882" alt="screenshot_4649" src="https://github.com/bluesky-social/social-app/assets/4497705/3a6126a9-0c51-4d8f-9c94-1998e80ee8c3">

**Comment by Soulflare3** [comment]
Also experiencing this one seemingly randomly, both via web and android app, though not always both at once. Sometimes, if I search for a user by name or handle they do not appear in search results on either the posts or users tab. If I click on a link either in-app or externally to their profile, the profile loads normally.

This seems to be mitigated somewhat on PC as the "live" search can sometimes find these accounts, but if you actually hit enter and go to the search page they are not found.

Example putting in a full handle and hitting search:
![image](https://github.com/bluesky-social/social-app/assets/1958728/2b15ff2d-3626-4a65-8fc3-d2c79e43a638)
Live search finding the account as I'm typing (but not the search page)
![image](https://github.com/bluesky-social/social-app/assets/1958728/c75d1afd-6779-4a12-a55c-00bd24fcadd2)
Another example, same situation
![image](https://github.com/bluesky-social/social-app/assets/1958728/431d273c-dda2-49c0-9a49-59c726a722a0)

**Comment by pfrazee** [comment]
Yeah we're working on this. Pretty irritating to be sure

**Comment by mschwendener** [comment]
(same as https://github.com/bluesky-social/social-app/issues/715, I think)

**Comment by mschwendener** [comment]
I think this can be closed as solved. 

I'm not finding basoon, but this must be because the account has been deleted/renamed. 

Working fine for me now, also for akuuttigeriatri and isaacyote, the examples from others' posts.

**Comment by pfrazee** [comment]
Cool Cool

**Comment by jesusib** [comment]
I don't think this issue is fully resolved, guys :(

![{A309FF27-A166-460A-80CE-C73885F6D914}](https://github.com/user-attachments/assets/62b5d83b-b6ee-4f3b-ab7a-8c5f38fd386f)
![{D5ACF876-DC36-4C7D-B3ED-3ABD2C1E3937}](https://github.com/user-attachments/assets/99100fda-fed2-4e72-afd9-ff3ae347acb7)

I can't find a lot of people I have _in that other social network_

**Comment by surfdude29** [comment]
@jesusib FYI I posted about this here as I'm also not able to find that user in search, and they don't appear in autocomplete either:

https://bsky.app/profile/surfdude29.ispost.ing/post/3l7lmtzc5de2c

**Comment by surfdude29** [comment]
@jesusib From the thread above, the explanation as to why the user isn't showing up in search etc is that they don't have a profile record. Profile records have been automatically created when a user signs up in the official app since February 2024.

However, [@skaldothor.bsky.social](https://bsky.app/profile/did:plc:7ekzh5pdbqd7nrxi7vgpii4o) signed up [in October 2023](https://internect.info/did/did:plc:7ekzh5pdbqd7nrxi7vgpii4o) and seems not to have updated their profile since then. The explanation of how they can fix this [comes from one of the devs,  @esb.lol](https://bsky.app/profile/esb.lol/post/3l7lr7cvvij25):

> yeah it's this — our onboarding creates a profile record for users, but folks signing up through other apps or through the API may not have a profile record

> they can bump it by editing their display name or other profile info and saving it again, that will get them indexed in search

So for instance, just editing their display name to "skaldothor" would be enough to create a profile record and get them indexed; they don't have to write anything in their bio or upload an avatar.

**Comment by akaimizu1** [comment]
I tried doing the same. I'm an early BlueSky adopter, and I Edited my Profile, today, multiple times. I still don't seem to show up in people's search.

**Comment by Soulflare3** [comment]
> I tried doing the same. I had friends who were searching for me and couldn't find me. I literally have to share a direct link to my profile in order for them to find me. But I'm not showing up in any searches. I'm an early BlueSky adopter, and I Edited my Profile, today, multiple times. I still don't seem to show up in people's search. Does it take a day for it to get indexed?

if your username is `akaimizu` on bsky as well, it is showing in search
![image](https://github.com/user-attachments/assets/494b75f9-3cef-47d2-b0fe-5b06ea5d5e06)
![image](https://github.com/user-attachments/assets/4e904f84-de3a-4a6e-b42c-c2a7cf61793f)

(Assuming this is correct because of this post, but please correct me if needed)
![image](https://github.com/user-attachments/assets/d2978750-0c7f-4ff7-9b79-83acf146799c)

**Comment by akaimizu1** [comment]
> > I tried doing the same. I had friends who were searching for me and couldn't find me. I literally have to share a direct link to my profile in order for them to find me. But I'm not showing up in any searches. I'm an early BlueSky adopter, and I Edited my Profile, today, multiple times. I still don't seem to show up in people's search. Does it take a day for it to get indexed?
> 
> if your username is `akaimizu` on bsky as well, it is showing in search ![image](https://private-user-images.githubusercontent.com/1958728/386239928-494b75f9-3cef-47d2-b0fe-5b06ea5d5e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTY5MjgsIm5iZiI6MTczMTU5NjYyOCwicGF0aCI6Ii8xOTU4NzI4LzM4NjIzOTkyOC00OTRiNzVmOS0zY2VmLTQ3ZDItYjBmZS01YjA2ZWE1ZDVlMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTUwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYxZjNmNWUxNTJjZTFhOWYzYjM5MTg1YTNhMWY2NmVhYThjY2M0NDRhYmRjNTM1YjBiMjE2YzM2MDI2Yjk5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1VBFFGIZG2UFYA99BS3-21RKi52ke-tqtseFcgRwd5c) ![image](https://private-user-images.githubusercontent.com/1958728/386239963-4e904f84-de3a-4a6e-b42c-c2a7cf61793f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTY5MjgsIm5iZiI6MTczMTU5NjYyOCwicGF0aCI6Ii8xOTU4NzI4LzM4NjIzOTk2My00ZTkwNGY4NC1kZTNhLTRhNmUtYjQyYy1jMmE3Y2Y2MTc5M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTUwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdkM2I2OWE3YjhkYTI4Mjk4NzIyODM4OGM0MGNkMWQ0YjlhZTRjZWI5YzUzYmU1MTgxYTM0NjRmNGFhMGZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LXidn-x-77Wp3fF-J95vHe8rwVtIRCso14q49TbT8ag)
> 
> (Assuming this is correct because of this post, but please correct me if needed) ![image](https://private-user-images.githubusercontent.com/1958728/386240342-d2978750-0c7f-4ff7-9b79-83acf146799c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTY5MjgsIm5iZiI6MTczMTU5NjYyOCwicGF0aCI6Ii8xOTU4NzI4LzM4NjI0MDM0Mi1kMjk3ODc1MC0wYzdmLTRmZjctOWI3OS04M2FjZjE0Njc5OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTRUMTUwMzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM3NGExYWFmMzIwNGYzNTVkNDNjN2E0ODI0MjhkZjMzNmZlZTBiNjM1OGQ5NTQxNDQxYzQ5OGI5ZTczYTdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wz-cixIxG_xFsFQgBEDhJrbpcXWAoth5vVO_65RRulE)

Thank you. It is showing up now. I guess it really did take time for the indexing to happen.

**Comment by twfan** [comment]
Hi all, i ve setup handle bluesky settings with my own domain it is vobbatech.com success until update the handle. I already edit my profile, add image for profile and try to create post. But still cant find my user via search fields.

**Comment by echosend42** [comment]
Possibly the wrong place for this question but why can't I find a person, one I _follow_BTW, in the search field by a partial of their name? It will only find the person if the search string is the start of their name and I'm always forgetting this person's sort-of prefix before their name. This is via the web, not the app.
