### ISSUE TITLE
Rate limit exceeded – bug?

### ISSUE THREAD

**Issue by mschwendener** [bluesky-social/social-app#2221]
Hi

This looks wrong to me (not my account) https://www.reddit.com/r/BlueskySocial/comments/18jiq3a/rate_limit_exceeded 

From today

**Comment by pfrazee** [comment]
Hard to diagnose why this is happening without talking to the person involved, but we've tried to give pretty high limits. This might have been due to an app bug triggering extraneous requests (recently fixed). Otherwise not sure how to pursue this further atm

**Comment by joshismyhandle** [comment]
I cannot verify my email address due to this bug. When requesting a code to be emailed, I get the "rate limit exceeded" notification. I cannot comment or do anything in the app without verification so this is quite the bug.

**Comment by ETMitch21** [comment]
Has anyone ever found a solution to this? I have an account that I can not do anything with. It's been over 48 hours since I created the account now and I am still getting the same error. Now I have a domain and a username tied up to this account and obviously wouldn't be able to create another account. This seems to be a major issue with the platform that the developers appear to be ignoring. Digging in on Chrome Console, I thought these screenshots might help as a previous comment said they couldn't do anything unless talking to *THE* person experiencing the issue. 

Excited to use the platform but saddened by this issue.

![Image](https://github.com/user-attachments/assets/7690a252-0052-4fb6-bcd8-7e37cc11510f)
![Image](https://github.com/user-attachments/assets/9cf476f1-5882-434c-9451-6cdc2396e065)

**Comment by blu3r4d0n** [comment]
I've been having this issue for months. The workaround is to use my email instead of my custom domain handle.

**Comment by auntiesam23** [comment]
Any solution to this? Having the same issue on multiple devices/browsers and can’t use the site because of it.

**Comment by blu3r4d0n** [comment]
> I've been having this issue for months. The workaround is to use my email instead of my custom domain handle. Happy to provide any sort of debugging assistance.

I just tried logging in again and did not get the rate limit exceeded error!

**Comment by alwaysmuggedoff** [comment]
I`ve somehow been locked out of my account and am getting the Rate limit exceeded message on every attempt to reset my password

**Comment by almo2001** [comment]
I am now having this problem on an account I want to delete. There was some confusion about what the email was, I got "jeff" mixed up with "fred" in the email, and had to change the email. After that, I'm now unable to delete the account due to rate limit.

**Comment by LWFlouisa** [comment]
Nope its still happening here as well. I can't even post on Bluesky on the mobile sites.
