### ISSUE TITLE
Dark mode on application startup

### ISSUE THREAD

**Issue by maisondasilva** [bluesky-social/social-app#2292]
It would be nice to have an image with a darker background for those who use dark mode activated, because at night when opening the application it displays a bright image!

![Imagem do WhatsApp de 2023-12-24 à(s) 11 21 11_c3856e46](https://github.com/bluesky-social/social-app/assets/11423362/a59fdfd2-d825-4b87-9d4d-949b9325852e)

**Comment by pfrazee** [comment]
we'll have to see if that's possible. the splash is registered with the operating system and we may not be able to control it

**Comment by maisondasilva** [comment]
I use an app from Ubiquiti where opening the app changes according to light mode and dark mode, I just don't know how they did it!

**Comment by ansh** [comment]
We can do this via the `ios.splash.dark` flag in iOS and its equivalent in Android

https://docs.expo.dev/versions/latest/config/app

@pfrazee Im happy to take this on. Will be fun!

**Comment by pfrazee** [comment]
@ansh go for it

**Comment by pfrazee** [comment]
Closed by https://github.com/bluesky-social/social-app/pull/2448

**Comment by benharri** [comment]
There's still a full white screen before the splash image loads. I'm not seeing splash.dark changed in that PR

**Comment by scottdotjs** [comment]
I think this issue should be reopened. [This post by `@mukuuji.bsky.social`](https://bsky.app/profile/mukuuji.bsky.social/post/3klji4fvsdk2c) demonstrates why:

![bafkreidmvtj6xguczgxc6l3esds7aekk6gai2epxr7v2mz2hirebue45ru](https://github.com/bluesky-social/social-app/assets/32358661/47b9b4c1-8270-4036-ba36-8f0c7302a073)

To be slightly less tongue in cheek, for me as an Android user in dark mode, what I see after tapping the app icon is:
1. Dark blue screen with blue/white app icon
1. brief fade to completely white screen
1. night sky with stars
1. white butterfly appears
1. butterfly zooms to full white screen
1. fade to black dark mode of app.

So that's dark, full brightness, dark, full brightness, dark. It's actually quite unpleasant and I now tend to look away until the app is fully loaded. :(

**Comment by estrattonbailey** [comment]
Update here, we've tweaked this again, and the butterfly is now a deep, almost-black blue. Should prevent blinding users. Will be included in next release, pending any further changes 👍 

I don't think we've seen #2 before, I'll note that and investigate. Thanks for the details on that!

**Comment by scottdotjs** [comment]
Thank you! I've got a screen recording of the app starting up if you need a demo.

**Comment by estrattonbailey** [comment]
Oh that would be awesome if you don't mind uploading here 🙏

**Comment by scottdotjs** [comment]
Thanks Ben, that matched what I get.

**Comment by maisondasilva** [comment]
I see a clear image before the butterfly on my Samsung  

https://github.com/bluesky-social/social-app/assets/11423362/2b974a36-3313-491f-a142-60eef37e236a

**Comment by estrattonbailey** [comment]
Thanks y'all! Really appreciate it. We'll have a closer look 👍

**Comment by maisondasilva** [comment]
@estrattonbailey I think this could be opened again?

**Comment by estrattonbailey** [comment]
Oh sure! I'll keep myself assigned

**Comment by parion** [comment]
The latest update definitely helps by making the butterfly logo dark blue for dark mode users, but the white image described by @maisondasilva still exists.

**Comment by maisondasilva** [comment]
@parion Thanks
Yes, it was very good but I can confirm that there is still a white image

**Comment by haileyok** [comment]
This should be fixed now from https://github.com/bluesky-social/social-app/pull/3105. Please feel free to ping if it isn't in the next (not the one today/tomorrow but the _next_) update!
