### ISSUE TITLE
Some YouTube embedded videos not showing thumbnails

### ISSUE THREAD

**Issue by adamatic-me** [bluesky-social/social-app#2318]
**Describe the bug**
I posted a YouTube video, and the thumbnail is not showing in the card. However, I have seen other video posts where the thumbnail and title is extracted properly.

**To Reproduce**

1. See my post, with no thumbnail: https://bsky.app/profile/adamatic.bsky.social/post/3khi6noamtc2n
https://www.youtube.com/watch?v=fuSJ5k1orBk
Posted  6 years ago

2. See my other test post, with a thumbnail: https://bsky.app/profile/adamatic.bsky.social/post/3khi6juow6a25
https://www.youtube.com/watch?v=jNQXAC9IVRw
Posted  18 years ago

3. A different user's post with no thumbnail: https://bsky.app/profile/blowdart.me/post/3khi3c4y7cd2q
https://www.youtube.com/watch?v=xilvJ4zWytI
Posted 3 years ago

4. A different user's post with a thumbnail:  https://bsky.app/profile/tedunderwood.me/post/3khhukekhjy2d
https://www.youtube.com/watch?v=sKeZCRtprlw
Posted 6 months ago

**Expected behavior**

There should be thumbnails for posts 1. & 3. 

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/146130101/91bbf11b-c4ed-41e7-85ca-4c6f4a597819)

**Details**

 - Platform: Windows Firefox & MacOS Firefox & MacOS Chrome

**Additional context**

In addition to the videos which show no thumbnail, also the video title information is not extracted in the videos with no thumbnail.

I originally thought that this was related to upload date, but video 4. above, does have a thumbnail and is only 6 months old.

**Comment by adamatic-me** [comment]
Actually, while I thought that the issue was related to upload date, the link in 1. is only 6 months ago... so maybe the date of upload is not related to the issue.

**Comment by adamatic-me** [comment]
I thought maybe it was magically related to the new YT tracking info which I forgot to remove in post 1., but I removed it and the video data was still not extracted: https://bsky.app/profile/adamatic.bsky.social/post/3khibejef7p2t

**Comment by adamatic-me** [comment]
Last effort at helping: 

"I have a react native app that makes a media card for youtube videos which a user posts.

But only some video posts extract the video thumbnail, and title.. why could this be?"

https://chat.openai.com/share/b1ced529-b18b-4284-8a72-682c5596ee88

**Comment by pfrazee** [comment]
https://github.com/bluesky-social/social-app/pull/2328 Should fix this, as well as some updates by hailey to handle more URL types (m.)

**Comment by chairmanbrando** [comment]
Bumping this closed thread because I landed here after I tried to post [a video](https://www.youtube.com/watch?v=e_QQamQt5x4) but couldn't a card produced for it. The resulting placeholder stayed in place after posting and refreshing, so I deleted the post and went googling. I checked and the [video's metadata](https://mattw.io/youtube-metadata/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3De_QQamQt5x4&submit=true) *does* exist, so I'm not sure why Bluesky is having trouble with it!

![where-metadata](https://github.com/user-attachments/assets/0cad023f-c3ff-4a7c-9592-f60880be4fc2)

I checked the network log and it seems [the request](https://cardyb.bsky.app/v1/extract?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3De_QQamQt5x4) to cardyb.bsky.app is throwing a 500 error, so there must be something about this particular video this system doesn't like.

**Comment by wdcampbell3** [comment]
Dang, I'm having the same issue when posting a YouTube link via API. The post is going through but just a black box instead of the thumb... NOTE: If I copy/paste the youtube link on the front end it works fine. Any help would be AWESOME:
![Screenshot 2025-01-14 at 15 18 12](https://github.com/user-attachments/assets/02725bed-e747-43bc-9152-1778e4b0b88b)

Here's the POST request:

{
  "repo": "did:plc:3vcttmdypi7gf2225nq7yl7v",
  "record": {
"$type": "app.bsky.feed.post",
    "text": "Tired of YouTube post-production? Learn to automate thumbnails, descriptions, chapters & uploads! Save time, boost visibility, and focus on creating! #YouTubeAutomation #VideoMarketing #ContentCreation #SEOOptimization #YouTuberTips",
    "createdAt": "2025-01-14T22:19:52.069Z",
"embed": {
      "$type": "app.bsky.embed.external",
      "external": {
        "uri": "https://youtu.be/aDjBeTmDdzc",
        "title": "Tired of YouTube post-production? Learn to automate thumbnails, descriptions, chapters & uploads! Save time, boost visibility, and focus on creating!",
        "description": "YouTube Link"
      }
}
  },
  "collection": "app.bsky.feed.post"
}

**Comment by tayo123** [comment]
> Dang, I'm having the same issue when posting a YouTube link via API. The post is going through but just a black box instead of the thumb... NOTE: If I copy/paste the youtube link on the front end it works fine. Any help would be AWESOME: ![Screenshot 2025-01-14 at 15 18 12](https://github.com/user-attachments/assets/02725bed-e747-43bc-9152-1778e4b0b88b)
> 
> Here's the POST request:
> 
> { "repo": "did:plc:3vcttmdypi7gf2225nq7yl7v", "record": { "$type": "app.bsky.feed.post", "text": "Tired of YouTube post-production? Learn to automate thumbnails, descriptions, chapters & uploads! Save time, boost visibility, and focus on creating! #YouTubeAutomation #VideoMarketing #ContentCreation #SEOOptimization #YouTuberTips", "createdAt": "2025-01-14T22:19:52.069Z", "embed": { "$type": "app.bsky.embed.external", "external": { "uri": "https://youtu.be/aDjBeTmDdzc", "title": "Tired of YouTube post-production? Learn to automate thumbnails, descriptions, chapters & uploads! Save time, boost visibility, and focus on creating!", "description": "YouTube Link" } } }, "collection": "app.bsky.feed.post" }

I solved this by adding the "thumb" property to the "external" object. I fetch the thumbnails via the Youtube api, upload one of them to Bluesky as a blob, then attach the blob metadata as the "thumb" of the external embed.
