### ISSUE TITLE
Change: USK Level

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [bluesky-social/social-app#2660]
I'm obviously not 18, and since the USK Level is 18, I cannot download the app from the Google Play Store despite my parents allowing me to do it.

Competitors like Threads and Instagram are at USK 12.

**Comment by surfdude29** [comment]
I'm just a Bluesky user (and enthusiast who watches the repo), but until someone from the team is able to give you an official answer, I can point you to the [Terms of Service](https://blueskyweb.xyz/support/tos#who-can-use), which state that:

> To use Bluesky Social, you must be at least 13 years old and legally permitted to use Bluesky Social based on the laws in your country. If you are not yet an adult according to the laws of your country, your parent or legal guardian must read these Terms on your behalf. If you’re a parent or legal guardian, and you allow your child (who meets the minimum age for your country) to use the services, then these terms also apply to you, and you’re responsible for your child’s activity on the services.

I don't know the laws of Germany so I have no idea if someone under 18 would be legally permitted to use Bluesky, even with the permission of their parent or guardian.

> Competitors like Threads and Instagram are at USK 12.

I imagine that one of the main reasons that the Bluesky app is rated 18+ by USK is because Bluesky allows content featuring legal, consensual nudity and porn (unlike Threads and Instagram), and also some other types of content that would likely be taken down from its competitor platforms that are rated 12+.

For context, I see that both the Twitter and Mastodon apps are also rated 18+ by USK, I imagine because they also both allow nudity and porn:

![IMG_1930](https://github.com/bluesky-social/social-app/assets/149612116/4e3a7bed-c4d2-428e-a184-3ab8fee1f769)
![IMG_1929](https://github.com/bluesky-social/social-app/assets/149612116/c7d16b94-a99b-4ba0-917f-7d38df40187d)

I'm sorry that this is a disappointing response (although I should stress again that I'm just a user and this isn't official or anything), but given what I've said above I think it's pretty unlikely that the age rating will be changed.

**Comment by pfrazee** [comment]
Yeah that is indeed the case. We were assigned that rating on the basis of allowing adult content on the network. I'm sorry, @FleetAdmiralJakob !
