### ISSUE TITLE
Inserting a https-link in the web UI changes the link into the page title

### ISSUE THREAD

**Issue by jgarplind** [bluesky-social/social-app#4301]
**Describe the bug**

When pasting a full link (e.g. https://reactrouter.com/en/main/upgrading/future#future-flags) in the post composer, the link text is not pasted, instead the page title appears, and there is no obvious "linkiness" such as a blue color or a link card implying that things are in order.

**To Reproduce**

1. Grab yourself a nice link, such as https://reactrouter.com/en/main/upgrading/future#future-flags
2. Open the post composer
3. Paste the link

**Expected behavior**

The link should be pasted as-is.

**Screenshots**

Bad: 
![image](https://github.com/bluesky-social/social-app/assets/10069144/9ad41b4b-446c-4610-9e08-8c5d8ad9fe14)

Good (see below for how to achieve):
![image](https://github.com/bluesky-social/social-app/assets/10069144/0bd732f7-f4b1-42b2-abb7-19c3626efd7b)

**Details**

 - Platform: Desktop Windows Edge
 - Platform version: Windows 11, Edge 125.0.2535.67
 - App version: Build version: 1.84.0; Bundle info: e6d2618 (prod); Bundle date: 24052420; Platform: web

**Additional context**

Simple enough workaround:
1. Split the link into 2 parts: "h" and "ttps://......"
2. Paste them individually
3. Ta-da, expected behavior

**Comment by mary-ext** [comment]
seems to me the browser is copying *both* the URL and the page title, and because currently the composer isn't a plain text editor but rather a WYSIWYG editor pretending to be plain text, it has decided to paste the page title instead (in an attempt to get it to be a link)

I feel like we've had this issue before and the outcome was that we just don't know how to fix that yet, could you try seeing if Ctrl+Shift+V would give you the URL?

**Comment by mary-ext** [comment]
> I feel like we've had this issue before

Ah yes! This is a duplicate of #1321

**Comment by jgarplind** [comment]
Hey @mary-ext, thanks for getting back!

I'll close this and continue the discussion in the original issue.
