### ISSUE TITLE
Dedicated Trending Section

### ISSUE THREAD

**Issue by Mennaruuk** [bluesky-social/social-app#4703]
**Is your feature request related to a problem? Please describe.**

Currently, Bluesky lacks an Explore tab. There are some users who want to curate their feeds and only follow a handful of accounts. However, there are others (like me) who want to know the chatter around the town and what's popular at a particular moment.

**Describe the solution you'd like**

Twitter had a cool Explore section until recently. It used to take multiple factors into account, such as the volume of tweets discussing a particular subject, the rate at which they are being posted, user engagement, and what new topics are gaining lots of traction all of a sudden. It can also be personalized, so if you're living in one city you may see what's trending in your city rather than another city.

![Top-1024x877](https://github.com/bluesky-social/social-app/assets/52135169/ea829f0f-a9da-4b23-8171-0cc3af41f47b)

**Describe alternatives you've considered**

Discover exists, although it's not topical. The strength of Twitter's Explore section is that it shows a list of the most discussed topics or hashtags. That way, I can press any of them and be redirected to tweets about that particular topic. None of Bluesky's feeds can do this at the moment. 

**Additional context**

I want to mention that Twitter's Explore tab isn't merely a collection of the most popular posts about a topic sorted from most liked or retweeted to least. It's more of a random amalgamation of what's most trending.

Also, there are different themes to choose, such as Sports, News, etc.:
![promoted-tweet-samsung](https://github.com/bluesky-social/social-app/assets/52135169/cad82132-d378-4493-ba47-f20c8d59ce49)

**Comment by mmangopear** [comment]
Did the devs ever see this or add it to the roadmap? I feel like this is one of the few big missing holes

**Comment by gcjbr** [comment]
Would be down to work on it if I had confirmation this is of interest of the maintainers

**Comment by surfdude29** [comment]
FYI @pfrazee said earlier today:

> ... I've got a proposal for how to do Trending Topics. 🤞

https://bsky.app/profile/pfrazee.com/post/3l2zpqqyb762x

**Comment by borysmarceloherrera** [comment]
Please implement

**Comment by borysmarceloherrera** [comment]
How difficult is to create a tab and consume an api with a aggregated most commented words or a combination of 2 words.

It is very poor user experience without knowing what is going on. 

I think a World Wide tab and a Local tab based on users locations should be interesting.

**Comment by ajalaca** [comment]
While the trending feature is certainly attractive and has the potential to make Bluesky more active, we believe that the trending feature also carries a significant risk of inviting conflict and division among users.

We believe that such a conflict-free atmosphere is one of the main attractions of Bluesky and should be protected in the future, so we should be cautious about implementing the trending feature.

**Comment by miyacoz** [comment]
i'm curious if the 🦋 moderation team is capable enough of detecting and preventing the trending tab from being manipulated by scam and bots, which me and some other japanese folks on x - or who have evacuated from there - believe has happened over there at least for the language and region, and got worse especially after the billionaire started giving money to people on the platform.

since 🦋 isn't a money dispenser like x, i'm not quite worried about money motivated scam or bots would do that, however anybody (also their automated systems perhaps) with some radical intent would no matter how rich or poor they are, who and which i believe could convert our comfy home into another hell where people are always mad at something and fight each other every day, like @ajalaca kind of mentioned.

i know it's ultimately (and always) up to the HQ and what they want 🦋 to be, but personally i want them to do some research how differently social media has been used among regions and peoples, and make a decision that won't let them regret it, because i'm fond of this stellar sky so far.

---

also, as another web engineer, i wonder why the official app would need to implement the (controversial from my perspective) feature that seems buildable as a third party app or add-on or something, using the APIs and stuff offered by the HQ. or you can't with the supplies at the moment?

**Comment by yoshimoto-shinichi** [comment]
I think the trending feature on X is a big part of the problem with hate and conflict there. It's one of the worst things about X. I've seen so many people use it to stir up trouble just to get attention. That's why I came to Bluesky. If Bluesky adds a trending feature, I'll probably quit social media.

**Comment by pan090908097** [comment]
No, no need
That trend is already x and it is not working. 
It is being used as a political campaign tool and people are angry when they see scary incidents.

**Comment by Invertex** [comment]
I agree that it is a big source of conflict/division, and I'd made it possible to simply hide it in my Twitter extension, but it's also a powerful feature that can greatly improve reach for people/causes when something trends.

Perhaps by default it could filter out political terms? Just try to keep it to as low-conflict of topics in a "better than nothing" type of solution. Perhaps have popular trending tags be checked out by moderation to see if they should be added to a Trending filter and allow reporting of trending tags for that specific purpose as well.

Any time anything trends tends to invite some bad actors trying to sew conflict, Discovery/What's Hot isn't really much different in that respect. Trending would just be What's Hot, but for tags.

People should definitely have the option to disable the Trending section if it was implemented though, which I think would also help the issue. (and even the ability to set their own filtered tags in their profile settings)

**Comment by pan090908097** [comment]
In the old days on Twitter, newspapers and others would feed into the trending tags and provide biased summaries.It is important that each of us can choose what we want to see with the feed function.We don't need to impose.

**Comment by borysmarceloherrera** [comment]
Fellows, in any app or tool or system or backend or anything that we have many integrations and data we must see what is going on. That is called nowadays Observability. Bluesky show not be different. We need to know hot trending topics throughout the world like SARS COV19 pandemic. EPOX etc.

We are not living in rainforest anymore.

**Comment by pan090908097** [comment]
It is also a kind of neurosis to always try to observe anomalies in the whole world. There is no need for all users to constantly monitor the earth. I leave that to you. use X

**Comment by gigacee** [comment]
I get hot trending topics about world affairs (especially recent events are serious...) directly from experts in each field through books and videos, not from X Trending. It would be far much more efficient and reliable rather than wandering around in the desert of political maneuvering and public anger in SNS.

**Comment by BarterClub** [comment]
Trending should be added. Without the ads. This is a way to see what is going on in the world. It should be allowed to be hidden for users who don't want to see it.

**Comment by preetecool** [comment]
Trending topics is a great idea. To avoid unwanted exposure to tags, users may chose to avoid seeing trending topics, or chose what tags to add to their ignore list. 

I think it's a great way to start conversations about what people are talking about today.

**Comment by ajalaca** [comment]
While those who advocate trending believe that “all we need is a hide feature,” I believe that what is important is not simply visibility or invisibility, but rather the creation of a situation where the trending feature can be hacked to incite many users and incite division.

Visibility is a matter of personal discretion, but such an irreversible situation brought about by the trending feature is a problem that strongly affects the whole community.

**Comment by preetecool** [comment]
If we step back and assess the situation, it's clear that the community is already split between Bluesky and X. To prevent further fragmentation and encourage more constructive dialogue, it's worth discussing the need for a moderation system. This system should be designed to identify and address manufactured outrage and coordinated manipulation. While implementing such a system is undoubtedly challenging, the first step is to define what constitutes manufactured outrage, as well as coordinated efforts to manipulate or hijack trending topics.

**Comment by stevenlafl** [comment]
Here's my perspective. While true that people could manipulate the trending section, the major benefit is that it highlights ongoing critical news.

An active shooter situation, for example.

I think that as this platform grows it becomes part of social duty to highlight certain things such as this for common good. Can this be implemented responsibly?

**Comment by Invertex** [comment]
Okay, so apparently this discussion was completely ignored and a Trending section pull request was put up and approved within a week.
Was completely blindsided seeing the feature show up in the app today.
#7144 #7161 #7162

**Comment by stevenlafl** [comment]
> Okay, so apparently this discussion was completely ignored and a Trending section pull request was put up and approved within a week. Was completely blindsided seeing the feature show up in the app today. #7144 #7161 #7162
> 
> > Merry Christmas from us to you 🎄🎁💙 We launched Trending Topics today, and you can find it by tapping the search icon on the bottom bar of the app or the right sidebar on desktop.[![](https://camo.githubusercontent.com/15e6cfaf37ffb4523d8d1841a00783607685a797c15845cba0e958e4a11eb532/68747470733a2f2f692e696d6775722e636f6d2f764a3534516f342e706e67)](https://bsky.app/profile/did:plc:z72i7hdynmk6r22z27h6tvur/post/3le6bze3nus2c?ref_src=embed)— Bluesky [December 25, 2024 at 5:09 PM](https://bsky.app/profile/did:plc:z72i7hdynmk6r22z27h6tvur/post/3le6bze3nus2c?ref_src=embed)

This is incredibly unprofessional and disorganized behavior. @gaearon if this is an open source project, let it be that. If development is by Bluesky staff for bsky.app then close source it. What are we doing here folks? I rarely see this lack of cohesion. Consider learning from Torvalds.

**Comment by surfdude29** [comment]
> If development is by Bluesky staff for bsky.app...

Well... yeah? I'm baffled as to why anyone would find it strange that Bluesky developers – who, you know, *work for Bluesky PBC* – would develop a feature for the Bluesky app?

They accept many PRs from outside contributors, but of course the team of developers *who are actually paid to work on the app* drive the core development of it. How is this in any way surprising? 🤨

**Comment by stevenlafl** [comment]
> > If development is by Bluesky staff for bsky.app...
> 
> Well... yeah? I'm baffled as to why anyone would find it strange that Bluesky developers – who, you know, _work for Bluesky PBC_ – would develop a feature for the Bluesky app?
> 
> They accept many PRs from outside contributors, but of course the team of developers _who are actually paid to work on the app_ drive the core development of it. How is this in any way surprising? 🤨

Well, not my argument. This is an open source project that accepts issues and PRs. Not all github repositories have these two things turned on for precisely the reason you gave. If issues are ignored, it makes backlog grooming impossible and creates a giant mess. This is an organization issue. If what you are saying is correct, this issue should have been promptly closed. Clearly a reasonable expectation has been shattered. In fact, this issue shouldn't even be open right now. 

Also, very surprised by the unprofessional responses others gave. Why exactly do they think people contribute to open source projects? Should I not have submitted a patch to Valve's Proton when there was a crash bug running Half-Life Alyx just because the project is co-owned by two corporations?

Most understand that work primarily benefits a private corporation. Contributors expect they would have at least some input in return, or at the least some better backlog grooming. Otherwise we are all duplicating work that gets ignored. My core goal was to highlight that.

**Comment by surfdude29** [comment]
> If issues are ignored...

You seem to be implying that this issue was ignored by the devs. Obviously I can't know how much of the discussion here they have read, but I can say for certain that [someone sent a link to this issue](https://bsky.app/profile/sango.studio/post/3ldkndale422c) to one of the devs and [she replied](https://bsky.app/profile/hailey.at/post/3ldknkwpiac22), saying:

> this is definitely something that we are keeping in mind and being super cautious with. i absolutely don’t want to see this get leveraged in the wrong ways. can’t promise we will get it 100% right at first but i can absolutely say we’re doing this carefully with tightly scoped rollout and care

— @hailey.at, 18 December 2024

> If what you are saying is correct, this issue should have been promptly closed.

Many issues that are fixed by a PR are linked so that they're closed automatically when the relevant PR is merged. For whatever reason, this issue was not linked so it will need to be closed manually.

If your main concern is that this issue remains open after the feature has shipped, why not simply say that, and ask that the issue be closed? That would have been a more constructive course of action than making unfounded accusations of unprofessional behaviour.

**Comment by stevenlafl** [comment]
> If your main concern is that this issue remains open after the feature has shipped, why not simply say that, and ask that the issue be closed?

Excellent suggestion, and way more of a proper and effective response. You are right to point out a number of things here and I missed that workflow minutea. 

Thank you for the high quality response.

So, my request is that this issue be closed.
