### ISSUE TITLE
Volume control for media player

### ISSUE THREAD

**Issue by HybridEidolon** [bluesky-social/social-app#5285]
**Is your feature request related to a problem? Please describe.**

Currently it is possible to mute and unmute videos embedded in posts, but it is not possible to adjust the playback volume.

**Describe the solution you'd like**

Add a pop-out volume fader as is frequently found on other video player interfaces on the web.

**Describe alternatives you've considered**

Writing a GreaseMonkey script to add a volume control, but obviously this doesn't work on the native apps.

**Comment by sighlessm** [comment]
Every video has been blasting me so thanks for opening this.

I would add that it ought to save your selection and apply to ever video thereafter, too. So if I set it at 70% volume for one video, the next video I play is also at 70% volume

**Comment by netux** [comment]
Something I added on my ticket about this: Please use some sort of logarithmic conversion for the volume slider → video volume, since audio perception isn't linear!
[Dr. Lex has a great blog post](https://www.dr-lex.be/info-stuff/volumecontrols.html) explaining why this is needed, and provides a simple, cheap-ish formula to convert between the two:
```ts
video.volume = Math.pow(slider.value /* in the range [0, 1] */, 4);
```

**Comment by informatdcs** [comment]
Until this gets pushed into production.. I made an extension, free and no data collection of course.
https://chromewebstore.google.com/detail/bluesky-better-video-and/adfccfhgcdigpnopaibalgimjioiddcg

**Comment by brw** [comment]
@informatdcs it's already in production. You might be running into the bug where it won't show up if your device has touch screen support. There's an open PR for it here https://github.com/bluesky-social/social-app/pull/5919

**Comment by informatdcs** [comment]
Sure it does! Oh my god... I just read the feature request and since I've been using it like that since the start.. I didnt bother to check with anyone else or other browser, well... I made an extension 🤣 I will be adding comments on all the store pages saying that it is an issue in some browsers and a solution is WIP.

Thank you @brw

**Comment by brw** [comment]
I also created a userscript for it in the meantime that overrides `navigator.maxTouchPoints` to be 0 fwiw https://greasyfork.org/en/scripts/518378-spoof-bluesky-mobile-detection

**Comment by informatdcs** [comment]
Just updated Edge chromium and it seems fixed!

**Comment by brw** [comment]
Did `navigator.maxTouchPoints` report 256 for you before? Someone else mentioned they had that and it's supposedly a bug in Windows/Edge. Perhaps that just got fixed then https://github.com/bluesky-social/social-app/issues/5856#issuecomment-2495542110

**Comment by informatdcs** [comment]
For me it reported just 2, but right now it reports 0, I'm on a desktop so
it should report 0 since I'm not using any touch sensitive controls.
