### ISSUE TITLE
Uploading Images Mangled By Possible Fingerprinting

### ISSUE THREAD

**Issue by Gramps** [bluesky-social/social-app#5928]
### Steps to Reproduce

1. Use a browser hardened against fingerprinting techniques
2. Upload image or link to an image
3. BlueSky mangles the image
4. Turn off fingerprinting protections
5. Upload image or link to an image
6. BlueSky does not mangle the image

### Attachments

![Screenshot from 2024-10-24 11-27-25](https://github.com/user-attachments/assets/c3e47669-fbd3-4864-8a33-a433d636421c)
![Screenshot from 2024-10-24 11-27-38](https://github.com/user-attachments/assets/e26ef77b-f988-4752-b499-55b1e81a3cc9)

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

Whatever the main bsky.app site is.

### Additional Information

This behavior occurs on no other website nor app (like Discord) that I use anywhere with the same browser.  Most likely the scripts BlueSky is using for such image uploading trigger a rejection due to privacy techniques.

**Comment by Tamschi** [comment]
Bluesky uses a canvas element to resize and recompress images before upload, here: https://github.com/bluesky-social/social-app/blob/fa4cca11fedb78b31b7b606eafa74ebc17435f24/src/lib/media/manip.web.ts#L115-L134 I'm not sure what about this triggers the protection, as fingerprinting usually involved drawing some text. Maybe an `OffscreenCanvas` would be unaffected?

Discord sends all files uploaded on web verbatim (rejecting ones that are too large) and most other websites still upload the original and do the recompression serverside. That bypasses this problem here, but potentially introduces other (security, privacy) issues.

**Comment by Gramps** [comment]
Yeah, I sometimes also get warnings about some sites wanting to use canvas so that would make sense; though none of those sites do any kind of image uploading whatsoever.  My bank, for instance, is one.  I found it odd that only BlueSky was affected by this.  Hopefully that can be fixed as I am not interested in relaxing security for this feature.

**Comment by mary-ext** [comment]
Canvas fingerprinting is mitigated by either blocking the canvas functionality entirely or rendering it completely useless, the latter is what seems to be going on.

Ideally we would've just backed out of compression, but this would've been easier if canvas was blocked rather than rendered useless. Given that the use is on preventing fingerprinting, I'd doubt we'd see a way to check for this specific scenario.

So the only way is for you to disable canvas fingerprinting on Bluesky.

**Comment by Gramps** [comment]
Thanks for that explanation! Yeah, I see no reason to lessen security for any website, let alone social media. I guess I can just redirect users to the Mastodon versions of the posts.
