### ISSUE TITLE
Strange UX for Mod List Mute/Block Actions

### ISSUE THREAD

**Issue by jamesonwilliams** [bluesky-social/social-app#6167]
### Steps to Reproduce

1. Go to a mod list like [this one](https://bsky.app/profile/skywatch.blue/lists/3l53cjwlt4o2s)
2. Click the "Subscribe" button in the top left, next to an overflow menu

Actual behavior: populates a secondary menu with Mute/Block options, which are actions that don't follow from the verb "subscribe"

Expected behavior: "subscribe" would follow all of the accounts.

### Attachments

<img width="1054" alt="Screenshot 2024-11-08 at 11 39 52 AM" src="https://github.com/user-attachments/assets/90e2e60f-bde1-46ef-be77-2cbc209b455a">

### What platform(s) does this occur on?

iOS, Android, Web (Desktop), Web (Mobile)

### Device Info

I tested on Chrome Mac OS X and iPhone 13 mini, but it is not device-specific.

### What version of the app are you using?

iOS 1.92.1.530 89cff31b6 (prod) / Web Build version: 1.92.1; Bundle info: dfbfcdd (prod); Bundle date: 24110420; Platform: web

### Additional Information

While the user would expect "subscribe" to follow all of the accounts, the block/mute are the useful actions on a mod list.

So the fix here is likely to change the text from "subscribe" to "moderate", or something along those lines.

**Comment by altercation** [comment]
Correlated to this bug is the settings UI. While "blocked" and "muted" are top level items here, the moderation lists are not subsequently separated into "muted" vs "blocked". This is sort of an inverse discoverability issue where, in order to find out the state of the moderation list subscription, you have to click all the way into a list to find out which was selected.

While this correlated settings issue might warrant a separate bug report, it felt related enough to a rethink of this UI issue around the term subscribe that I thought it worth adding as a comment here.

<img width="578" alt="Screenshot 2024-11-10 at 21 34 05" src="https://github.com/user-attachments/assets/6f562582-e718-49b5-b595-30be64fa7115">

**Comment by scottdotweb** [comment]
I think this is the same as #5269.

**Comment by jamesonwilliams** [comment]
@scottdotweb - it is! Will close.
