### ISSUE TITLE
[Localisation] ‘Adult’ string untranslatable

### ISSUE THREAD

**Issue by smileyhead** [bluesky-social/social-app#6183]
### Steps to Reproduce

1. Open the post composer
2. Attach an image
3. Click Labels
4. Observe the ‘Adult’ string under ‘Adult content’

### Attachments

![image](https://github.com/user-attachments/assets/4487dcd4-6b80-4f90-a994-c0e85d0c844b)
Location of the string in-app.

![image](https://github.com/user-attachments/assets/5617cdf6-f8b7-4cc2-9e0c-3b4dadbd083f)
Bsky strings (after `yarn intl:extract` has been run) sorted alphabetically – as you can see, the ‘Adult’ string is missing.

### What platform(s) does this occur on?

iOS, Android, Web (Desktop), Web (Mobile)

### What version of the app are you using?

Build version: 1.93.0; Bundle info: 7731136 (prod); Bundle date: 24110818; Platform: web

### Additional Information

The ‘Adult’ string under the post composer's Labels modal is not currently present in the language files, and is therefore untranslatable.

**Comment by surfdude29** [comment]
I'm not exactly sure what's going on here, because in the code the string is `Porn` rather than `Adult`:

https://github.com/bluesky-social/social-app/blob/bf0a847ffe25a136caed8824d7f725ebef8490cf/src/view/com/composer/labels/LabelsBtn.tsx#L158-L161

And `Porn` is what I see on web, but I see `Adult` in the iOS app 🤔

Maybe there's an Apple restriction that doesn't allow the use of the word `Porn` in UI elements? (I don't have an Android phone so I can't check what it looks like there.)

**Comment by auroursa** [comment]
It has been renamed to Porn in the latest commit. I checked and confirmed that it can be translated (in Chinese as an example)
![image](https://github.com/user-attachments/assets/f6e978e2-9e29-42f7-bdae-4d9967323ca3)
![image](https://github.com/user-attachments/assets/3994d1e0-7edd-4617-939b-158ec8dd6d74)

**Comment by smileyhead** [comment]
Kinda silly that it was changed and a new version released to the public before the new term could be localised, but alright.
