### ISSUE TITLE
Guideline for use of "tag" versus "label"

### ISSUE THREAD

**Issue by monty241** [bluesky-social/social-app#6262]
### Steps to Reproduce

There are references to both "label" as well as "tag" in the English translation.

Are these different concepts? If so, what are their semantics? If not, can they be merged to one word?

In Dutch, a "tag" is often translated as "label", as is the English "label".

Sample of "Label"

![image](https://github.com/user-attachments/assets/ead4013d-8860-4b88-b755-6a0a5a07bca6)

Sample of "Tag"

![image](https://github.com/user-attachments/assets/f5b75235-1a59-42fd-b898-41db894de5c1)

### What platform(s) does this occur on?

iOS, Android, Web (Desktop), Web (Mobile)

### What version of the app are you using?

main

**Comment by Tamschi** [comment]
They're distinct concepts.

> Labels are annotations on users and content. They can be used to hide, warn, and categorize the network.

"Labels" are mainly a moderation tool, like "Rude" or "Intolerance", but a few can also be self-applied to warn about adult and graphic media (which then is hidden or behind a click-through by default). There are also positive labels for example by https://bsky.app/profile/yardcrow.com.

Hashtags are "tags", but "tags" is a bit more general, since the protocol also allows you to add tags to posts outside of the text and there (formally) without a `#`. Bluesky doesn't yet have UI for the latter though, and they may well end up with a purely visual "#" since they more or less do behave just like hashtags.

**Comment by monty241** [comment]
Thank you! Labels are for labeling, tags are hastags and for content (text). I will add it to the glossary.
