### ISSUE TITLE
Add Aragonese Language (an, arg)

### ISSUE THREAD

**Issue by Juanpabl** [bluesky-social/social-app#6374]
### Describe the Feature

I'd like to ask for a Bluesky localization in Aragonese (ISO codes: an, arg).
I have worked in many l10n projects before, and would work in this one too.

**Comment by surfdude29** [comment]
It's always great to see another Bluesky localisation!

When the translation is finished, submit a PR and, given their previous stance on accepting new localisations, I think it's likely that the devs would accept it 💫

The only thing that they usually ask for is that the PR is reviewed by at least one other native speaker.

Also, apologies if you're already aware of this, but I have one quick tip: there's no need to translate any of the strings where the line starts with `#~`. These are obsolete strings, they no longer appear in the app but they haven't been removed from the message catalog yet.

**Comment by surfdude29** [comment]
I gave a longer (perhaps too long) [answer in another issue](https://github.com/bluesky-social/social-app/issues/6361#issuecomment-2479560235) on this topic but the short answer is that Crowdin is not officially used by Bluesky so far, however you're welcome to set up a project on Crowdin if you'd prefer, in order to make collaboration with others easier.

Or you can simply open a PR and then respond to review comments here on GitHub. This is what I do when I'm updating the French localisation.

**Comment by Juanpabl** [comment]
I close issue after [PR](https://github.com/bluesky-social/social-app/pull/6638) has been merged. Thanks!
