### ISSUE TITLE
bsky.app doesn't load on Firefox

### ISSUE THREAD

**Issue by machinestops** [bluesky-social/social-app#6429]
### Steps to Reproduce

1. Open bsky.app on Firefox 132.0
2. Observe
![image](https://github.com/user-attachments/assets/4343db65-1496-4646-9ace-fa29c05c7a07)

### Attachments

![image](https://github.com/user-attachments/assets/14fc61b8-8f0b-4349-bf6e-cbf4e07a28ce)
This is the console with tracking protection enabled.
![image](https://github.com/user-attachments/assets/f3ff6520-836d-444a-96cf-72c578dd2f95)
This the console with the tracking protection disabled.

The 

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Void Linux

### What version of the app are you using?

Not possible

### Additional Information

Also occurs in Private Browsing, and after clearing cookies and site data. Occurs regardless of  if extensions are enabled or not. Occurs regardless of if Enhanced Tracking Protection is enabled or not.

**Comment by machinestops** [comment]
I've changed the issue title because the failure to load still occurs when Enhanced Tracking Protection and Ublock Origin are disabled. The failed requests sent to sentry.io don't enable the site to function if they succeed, meaning the site isn't failing due to these requests failing (which fail due to CORS), so the issue doesn't lie with CORS. I feel like the sentry.io requests not being covered by the CORS policy might be an issue of its own. 
![image](https://github.com/user-attachments/assets/49f3df96-ec24-4d27-b25d-932607c4b04b)
![image](https://github.com/user-attachments/assets/2109a90f-654f-451d-806b-9e668d409bde)

**Comment by LegendEffects** [comment]
This is a problem with what Firefox is reporting for `navigator.languages` or `navigator.language`, this gets passed into `new Intl.Locale` which is throwing due to this invalid value, I'm unsure how Firefox gets this value but this could go all the way down to being an OS setting.

**Comment by LegendEffects** [comment]
> Looks like @machinestops' computer is configured to support multiple locales: en-UK and en-US. Firefox's `navigator.languages` returns an array listing all of the device's locales `[ "en-UK", "en-US" ]` while Chrome's and Safari's `navigator.languages` return an array with just the one locale `[ "en-UK" ]`, ignoring the rest of the user's language preferences.
> 
> If the bsky.app website just wants one locale, it should either use `navigator.language` or only use the first item in the `navigator.languages` array.

This is already done in ExpoLocalization which is what BlueSky uses (https://github.com/expo/expo/blob/sdk-52/packages/expo-localization/src/ExpoLocalization.ts#L127-L177) the problem is likely that Firefox or wherever it sources this info from is reporting `["en-UK en-US"]` as a language instead of separating them.

**Comment by cpeterso** [comment]
> This is already done in ExpoLocalization which is what BlueSky uses (https://github.com/expo/expo/blob/sdk-52/packages/expo-localization/src/ExpoLocalization.ts#L127-L177)

Thanks for the link! I just stepped through that `getLocales()` function in the debugger and `getLocales()` correctly iterates through the locales array returned from `getNavigatorLocales()` without or throwing an error. But I wasn't able to reproduce this bug before either, even though my Firefox's `navigator.languages` is returning `[ "en-GB", "en-US" ]`.

I'm curious how @machinestops' first locale is `en-UK` instead of `en-GB`. Selecting "English (United Kingdom)" in Firefox's language settings (in `about:preferences`) will use `en-GB`.

⚠️ @machinestops: Did you manually set your Firefox's `intl.accept_languages` pref in `about:config` to `en-UK en-US`? That pref should be comma delimited like `en-UK,en-US`, not space delimited like `en-UK en-US`. Without a comma, Firefox will treat `en-UK en-US` as one long locale name. If I set my `intl.accept_languages` pref to `en-UK en-US`, I'm able to reproduce this bug.

**Comment by machinestops** [comment]
Nope, I've not manually changed my language values in about:config. It may be something added by something else. My distribution? I've reset that value to default, but the values in the about:config were comma _and_ space delineated, and resetting the value produced `en-GB, en`. With this value, space included, bsky.app loaded.

I set up this system with en-GB as my locale from the start, with no US locale. I imagine this probably snuck in somewhere in my Mozilla account or current OS install.

**Comment by cpeterso** [comment]
> Nope, I've not manually changed my language values in about:config. It may be something added by something else. My distribution? I've reset that value to default, but the values in the about:config were comma and space delineated, and resetting the value produced en-GB, en. With this value, space included, bsky.app loaded.

In that case, this bug report can either be closed as an issue with the Firefox client (TBD how the `intl.accept_languages` pref was set to `en-UK en-US`) or ExpoLocalization.ts `getLocales()` could be updated to handle this case, if it turns out to be common.

The space in the string should be fine as long as the comma is there.

> I set up this system with en-GB as my locale from the start, with no US locale.

I think Firefox automatically adds plain `en` after any `en-*` variant, in case some websites don't recognize the particular `en-*` variant.

**Comment by machinestops** [comment]
Yes, I'll close this issue. I checked the issues, and I couldn't find anything like it. I'll be combatting locales and Firefox distribution soon enough, so I may come back to this issue later to see if I can find the OS configurations that cause such a thing to occur, and see if they're common at all. I wonder if some script just appends the locale, causing one of the comma separated values to also have a space in them. Thank you for all the help!

**Comment by cpeterso** [comment]
I asked a Firefox web compatibility engineer about this issue. He tested Void Linux and says their Firefox packaging doesn't set the `intl.accept_languages` pref and the distro's locale environment variable uses comma-separated values, so he doesn't know where the `en-UK en-US` string came from. So it sounds like this is a weird configuration issue with your Firefox that hopefully doesn't affect other Firefox users.
