### ISSUE TITLE
Typing problem after pasting in a link into a reply.

### ISSUE THREAD

**Issue by elouangrimm** [bluesky-social/social-app#6661]
### Steps to Reproduce

1. Go to a post and press reply.
2. Type some text then enter a link. *(my link that I entered was https://bsky.app/intent/compose?text=testing, but I tried for other links and it did the same)*
3. After the link is pasted, the cursor goes to the beginning of the text and does not move (not by clicking at another place, by using arrow keys, etc.)
4. Any commands like `ctrl+c` or `ctrl+a` don't work, they just immediately unselect.
5. After deleting the reply and reopening a new one, you can type normally up until you paste in a link.

### Attachments

[Screen recording 2024-11-23 6.09.45 PM.webm](https://github.com/user-attachments/assets/a1434f21-ec18-4901-a2af-7f8f023403f1)
Above is a screen recording of the bug.

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Chromebook, up to date (127 or so)

### What version of the app are you using?

1.94.0

**Comment by amhyder** [comment]
I've tried to reproduce this on Windows using Firefox and Chrome but was unable to replicate this behavior. I tried a combination of using ctrl+v, windows+v, and right click + paste. All three of these options worked without issue.

@elouangrimm A couple questions for you so that the team might be able to help get to the bottom of this:
- You mentioned you're using a chromebook. Are you also using chrome as your browser? 
- Do you still encounter this issue when using the standard ctrl+v paste shortcut? What about ctrl+shift+v?

**Comment by elouangrimm** [comment]
Hi, So it's not as much _copying_, it was when I was trying to select my message so that I could paste it in again to not retype it. I believe you _could_ copy, but the problem was/is you can't select, so you don't have anything to copy. I am using Chrome.
[Screen recording 2024-11-24 7.15.08 AM.webm](https://github.com/user-attachments/assets/bbc957c2-83a9-4161-95e8-51fc0ab1ca01) *(you can play this a 2 times speed **;)** )*

**Comment by Llambi** [comment]
Hi, I've tried to reproduce this on macOS Sequoia 15.1.1 + Arc Browser and It works ok 😅

Uploading Screen Recording 2024-11-24 at 21.47.17.mov…

**Comment by elouangrimm** [comment]
Yeah, I'm pretty sure that the problem was I had a chrome extension (https://chrome.google.com/webstore/detail/onhibligfgppldbkcogdhjbfboeoicno) that broke this, and when I disabled this, the problem fixed. Thanks to everyone that tried to help out. :)
