### ISSUE TITLE
Add stale-bot to this repo to remove the noise

### ISSUE THREAD

**Issue by pstashp** [bluesky-social/social-app#7295]
This repo has 1.5k issues and 279 PRs.  Pretty sure 99% of them are low-quality items from random people, but it'll be rude to just close it directly.

**Why not add a stale-bot to remove these items within 1 month?** For items that are interesting but the team simply doesn't have time to review, pin it.  

This will also give us some impression on what you are guys might be interested in, or what issues are worth tackling.

Otherwise, I don't see a point in making this proof-of-concept product open source.

**Comment by cooljeanius** [comment]
https://fvsch.com/stale-bots
https://nostalebots.xyz/

**Comment by auroursa** [comment]
There are some PRs and issues that haven't been handled properly, but using a stale bot might hide real problems. For contributors and issue reporters, having a bot close their work automatically can feel worse than a manual closure, where at least the developer likely looked at the PR or issue briefly and quickly assessed what happened.

The delay in resolving most PRs and issues is usually due to more pressing problems taking priority. These contributions remain important as they improve one or more features. PRs and issues also serve as independent discussion spaces—if a PR or issue significantly impacts many users, it naturally draws more attention and discussion, eventually catching the developer’s focus.But with the use of a stale-bot, these issues might be prematurely closed simply due to inactivity over time.

**Comment by gaearon** [comment]
In my experience stalebots are great at one thing, which is “making the number go down”. They’re only marginally beneficial for most other things — like accurately tracking defects, prioritizing work, and improving discussion and contribution quality.  And in many cases they’re actively harmful, such as when high quality reports get closed. The marginal benefit, in my view, isn’t worth that downside.

It’s true we’re not prioritizing very close GH issue management at this point. We treat it as another input source alongside the bugs that people report in the app and elsewhere. We try to stay aware of what’s happening here but don’t communicate a lot. I think we’ll be able to catch up on this eventually but for now I don’t think it is pressing.

As for contributions, we have an eye on the PR queue. Contributions which don’t require product decisions, that are clearly thoughtful, and are obviously well-tested have a higher chance of getting through. But we don’t have a ton of time to prioritize shepherding contributions to get to that stage at this point.

I’d say there’s still a lot of value in the product being open source even if we’re not very actively engaging with the issue queue on GitHub. People can learn from the code and can fix bugs (we’ve taken many nontrivial bugfixes, especially where the effort has been made to demonstrate it was well-tested). And if time allows, we might also be able to get better at GH issue management in the future.

Hope that helps.
