### ISSUE TITLE
Blur on "Warn" filters doesn't always blur well.

### ISSUE THREAD

**Issue by jetpacktuxedo** [bluesky-social/social-app#882]
**Describe the bug**
When a blurred post is near the bottom of the screen some of the blur is lifted and you can see the content underneath the warning

**To Reproduce**

1. Find a post with warned content
2. scroll that content partially off-screen
3. observe that the blur fades away towards the window border allowing you to see underneath it
4. stop looking at Fuck Alf

**Expected behavior**

Blur should remain constant even as the content is being scrolled off-screen

**Screenshots**

Fully blurred as Fuck Alf is far enough from the window border to remain fully blurred
![image](https://github.com/bluesky-social/social-app/assets/3813932/450ea8e4-eae8-4f76-bbee-e7ba6c0909bf)

Smaller window size with the window scrolled so that the image touches but does not pass the screen edge, image remains fully blurred
![image](https://github.com/bluesky-social/social-app/assets/3813932/6d1f7625-3e42-448b-9ba2-38eb89e8a103)

Fuck Alf's hand, knee, and chest pretty plainly visible through the blur as the image is scrolled off screen
![image](https://github.com/bluesky-social/social-app/assets/3813932/ddd75b3a-29ea-4e32-af6e-75ceb2772042)

**Details**

 - Platform: windows firefox 
 - Platform version: windows 10, firefox 114.0.1 
 - App version: Build version: 1.31.0; Platform: web

**Additional context**

I carefully aligned my screenshot such that I didn't drop Alf hog in my bug report.

**Comment by KevSlashNull** [comment]
Just encountered this too (unfortunately D:). Seems to be a Firefox-only bug, since this doesn’t happen in the app or in Chromium. I’m on FF109.09b, Ubuntu 22.04.2, Build version: 1.33.0; Platform: web.

The `backdrop-filter` seems to be borked in this exact use case in FF for now. There are [multiple backdrop-filter in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1816630) and one particularly [similar issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1794432).

As an alternative, using `filter: blur(100px)` on the image directly instead of an overlay works fine but it also darkens the image quite a lot. (The [post used below](https://bsky.app/profile/ruffyflufferson.bsky.social/post/3jyknyi3jye25) for demo, contains nudity.)

| `backdrop-filter: blur` on overlay | `filter: blur` on the image |
| --- | --- |
| ![image](https://github.com/bluesky-social/social-app/assets/28510368/e384e0c4-412b-4e26-9497-f6c98640040e) | ![image](https://github.com/bluesky-social/social-app/assets/28510368/29383da0-3c8e-4d86-b0b6-46fe16328324) |

**Comment by pfrazee** [comment]
Marking as "wontfix" but the more accurate answer is we're replacing this behavior
